version: '3'
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - app-tier
    volumes:
      - ./data/mongodata:/data/db
    ports:
      - 27017:27017

networks:
  app-tier:
    driver: bridge
